on:
  push:

name: Test

jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: https://github.com/LibreKitten/LibreKitten-gui.git
    - name: Test
      run: git branch
